### ISSUE TITLE
Make the same class for upload and result file parameter

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-dotnet#17]
Currently there are two classes for upload file and result file. It is exactly the same entity. File should be one class.

https://github.com/ConvertAPI/convertapi-dotnet/blob/18b930beda7e230c063ea2f4ba0b810cb46b3014/ConvertApi/Model/ConvertApiResponse.cs#L13
https://github.com/ConvertAPI/convertapi-dotnet/blob/18b930beda7e230c063ea2f4ba0b810cb46b3014/ConvertApi/Model/ConvertApiUpload.cs#L3

**Comment by tomasr78** [comment]
Please provide a real-life case of how this improves implementation or development using the library?

**Comment by JonasJasas** [comment]
Unable to provide. Can be closed.

**Comment by tomasr78** [comment]
Implemented https://github.com/ConvertAPI/convertapi-dotnet/blob/master/ConvertApi/Model/ConvertApiFiles.cs
