### ISSUE TITLE
Make DevOps integration on Azure to automatically build and publish to NugGet

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-dotnet#18]
Make DevOps integration on Azure to automatically build and publish to NugGet on master change.

From nuget description

Note: To push packages to nuget.org you must [use nuget.exe v4.1.0](https://www.nuget.org/downloads) or above, which implements the required [NuGet protocols](https://docs.microsoft.com/en-us/nuget/api/nuget-protocols).

**Comment by JonasJasas** [comment]
Done
