### ISSUE TITLE
Extend ConvertApiParam for File parameter

### ISSUE THREAD

**Issue by JonasJasas** [ConvertAPI/convertapi-dotnet#2]
There is no way how to add more than one file to ConvertApiParam.
Extend ConvertApiParam class to ConvertApiFileParam and accept only one parameter, stream or string. The class will take care of File param names.

Now

`new ConvertApiParam("File", File.OpenRead(@"\source\test.docx"))`

Extended

```
new ConvertApiFileParam(File.OpenRead(@"\source\test.docx"))
new ConvertApiFileParam("http://www.mydomain.com/files.doc")
```

**Comment by tomasr78** [comment]
Implemented at #8
