### ISSUE TITLE
Do not pass any TimeOut to ConvertAPI and set HTTP Client timeout to 1800 seconds

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-dotnet#24]
Do not pass any TimeOut to ConvertAPI and set HTTP Client timeout to 1800 seconds. The idea is to use the default timeout of ConvertAPI if no timeout is set and to prevent HTTP Client request deadlock set default HTTPClient timeout to 1800 seconds.

If, however, timeout is set we handle it as before, pass a timeout to ConvertAPI and set HTTPClient Timeout to: `ConvertAPITimeOut+conversion_timeout_delta`

`conversion_timeout_delta = 10`

**Comment by tomasr78** [comment]
Also, move Timeout to properties as all ConvertAPI properties, makes no sense to use methods or configs to set timeouts that fully depend on Rest API timeout. This is very confusing when setting properties used one method but for Timeout - totally different scenario.

**Comment by tomasr78** [comment]
After this update need to update code snippets https://github.com/Baltsoft/CA-Web/issues/388

**Comment by Dattatraya77** [comment]
Hi @tomasr78, We are trying to convert 10 pages scanned pdf document to text file. It is converting fine from convertapi.com website dashboard. But when we convert same scanned pdf file from my python code, it is giving us read timeout(60 seconds) error. Could you please help me on this ?

**Comment by tomasr78** [comment]
You should post it in Python library issues https://github.com/ConvertAPI/convertapi-python/issues
