### ISSUE TITLE
Support Async conversion

### ISSUE THREAD

**Issue by nguyenquyhy** [ConvertAPI/convertapi-dotnet#28]
From what I can read in the code, Async parameter seems to be ignored. Is that correct that the library doesn't support async conversion at the moment?

**Comment by tomasr78** [comment]
The library supports Async methods, you can await them without blocking execution.

**Comment by nguyenquyhy** [comment]
No I am talking about Async parameter of ConvertAPI, which is a completely different thing from C# async/await concept for non-blocking calls.
