### ISSUE TITLE
Saving to a stream

### ISSUE THREAD

**Issue by SeanFeldman** [ConvertAPI/convertapi-dotnet#45]
Would be nice to reduce the dependency on the file system and allow saving to a stream for scenarios when the result is not stored locally but rather elsewhere, using services such as Azure Blob Storage or AWS S3.

**Comment by tomasr78** [comment]
This is already possible https://github.com/ConvertAPI/convertapi-dotnet/blob/master/Examples/FromStreamToStream/Program.cs

**Comment by SeanFeldman** [comment]
Wonderful. My bad, I didn't notice this in the documentation or when going through the API exploration.
