### ISSUE TITLE
Use Bearer authentication

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-dotnet#53]
Change `query` authentication to `bearer` authentication. 

`curl -X GET https://v2.convertapi.com/user -H 'Authorization: Bearer your_api_secret'`

Join secret and token parameters to one and name it as `AuthCredentials`

**Comment by tomasr78** [comment]
@paulius-petkus Merged to `master`; please build and push to `nuget.`

**Comment by paulius-petkus** [comment]
Done. 
![image](https://github.com/user-attachments/assets/17cf4107-3145-434e-a410-7a5d71caace3)

**Comment by paulius-petkus** [comment]
Done
