### ISSUE TITLE
Make SaveFiles method async

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-dotnet#9]
Make SaveFiles method async. Now it's saving files one by one through it could be done in parallel and saved several files at once. 

public static IEnumerable<FileInfo>SaveFiles(this ConvertApiResponse response, string directory)

**Comment by JonasJasas** [comment]
Downloading all at once will add almost no performance gain.

**Comment by tomasr78** [comment]
Moved to https://github.com/ConvertAPI/convertapi-dotnet/issues/16
